CREATE TABLE PERSON (
    ID VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    AGE INT NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    CONSTRAINT PK__PERSON_ID PRIMARY KEY (ID)
);