spring:
  profiles:
    active: dev
  resources:
    chain:
      enabled: true

faucet-pipeline:
  path-patterns: /javascripts/**, /stylesheets/**, /images/**

---

spring:
  profiles: dev
  thymeleaf:
    cache: false

faucet-pipeline:
  cache-manifest: false

logging:
  level:
    org.faucet_pipeline.spring.autoconfigure: debug

---

spring:
  profiles: prod
